# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

run-name: ${{ github.actor }} made some changes for the demo 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      id: coverage
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Print Action Outputs
      run: |
        echo "Coverage Badge: ${{ steps.coverage.outputs}}"
        echo "Coverage URL: ${{ steps.coverage.outputs.coverage-url }}"

        
    - name: Update README with Code Coverage Badge
      run: echo "[![Code Coverage](${{ steps.coverage.outputs.coverage-badge }})](${{ steps.coverage.outputs.coverage-url }})" > README.md

        
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'push'
      with:
        recreate: true
        path: code-coverage-results.md
